### ISSUE TITLE
App Drops Connection to RabbitMQ

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX#229]
We've seen cases where a network issue in the cluster causes the App to drop its connection to RabbitMQ and then can't find the transformation_requests exchange:

```
[2020-12-04 20:12:03,040] ERROR in rabbit_adaptor: Caught a channel error: (404, "NOT_FOUND - no exchange 'transformation_requests' in vhost '/'"), stopping...
Traceback (most recent call last):
  File "/home/servicex/servicex/rabbit_adaptor.py", line 182, in basic_publish
    mandatory=True)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2212, in basic_publish
    self._flush_output(self._message_confirmation_result.is_ready)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1340, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (404, "NOT_FOUND - no exchange 'transformation_requests' in vhost '/'")
```

RabbitMQ Reports:
```
2020-12-04 19:58:01.494 [warning] <0.6815.5> closing AMQP connection <0.6815.5> (192.168.38.188:59400 -> 192.168.23.186:5672, vhost: '/', user: 'user'):
client unexpectedly closed TCP connection
2020-12-04 19:58:06.666 [warning] <0.6711.5> closing AMQP connection <0.6711.5> (192.168.38.188:59346 -> 192.168.23.186:5672, vhost: '/', user: 'user'):
client unexpectedly closed TCP connection
2020-12-04 19:58:06.666 [warning] <0.6750.5> closing AMQP connection <0.6750.5> (192.168.38.188:59368 -> 192.168.23.186:5672, vhost: '/', user: 'user'):
client unexpectedly closed TCP connection
2020-12-04 20:00:29.569 [error] <0.6686.5> closing AMQP connection <0.6686.5> (192.168.38.188:59274 -> 192.168.23.186:5672):
missed heartbeats from client, timeout: 60s
2020-12-04 20:00:33.182 [error] <0.6789.5> closing AMQP connection <0.6789.5> (192.168.38.188:59386 -> 192.168.23.186:5672):
missed heartbeats from client, timeout: 60s
2020-12-04 20:00:33.353 [error] <0.6854.5> closing AMQP connection <0.6854.5> (192.168.38.188:59420 -> 192.168.23.186:5672):
missed heartbeats from client, timeout: 60s
2020-12-04 20:00:33.466 [error] <0.6906.5> closing AMQP connection <0.6906.5> (192.168.38.188:59444 -> 192.168.23.186:5672):
missed heartbeats from client, timeout: 60s
2020-12-04 20:00:33.520 [error] <0.6919.5> closing AMQP connection <0.6919.5> (192.168.38.188:59454 -> 192.168.23.186:5672):
```

**Comment by BenGalewsky** [comment]
Looks like we retry if creating a queue fails on a network error, but give up if the same error happens when creating an _exchange_

**Comment by BenGalewsky** [comment]
This is now fixed by
https://github.com/ssl-hep/ServiceX_App/pull/96
