### ISSUE TITLE
Transformer pods not terminating properly

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX#301]
- Transformer pods are not terminating even after all transformations for all input files are finished. This happens very small fraction of transformation requests (~ few percent). 

- Usual status of such transformation at the dashboard is something like below:
![Screen Shot 2021-06-10 at 12 43 10 PM](https://user-images.githubusercontent.com/54450665/121461276-802e1a00-c9e9-11eb-8d76-59f43868c284.png)
It just stays like this for several days.

- Frontend returns outputs properly so it seems like it's an internal issue of backend.

**Comment by AndrewEckart** [comment]
Suchandra reports that these transformers were blocking while trying to connect to RabbitMQ due to a missing queue:
```
File "/opt/conda/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1697, in _basic_consume_impl
self._flush_output(ok_result.is_ready)
File "/opt/conda/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1340, in _flush_output
raise self._closing_reason # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (404, "NOT_FOUND - no queue '9e85d78f-0fe7-4328-b6bf-da7772ddde52' in vhost '/'")
```

@BenGalewsky - could this be due to the changes in [ServiceX_App#96](https://github.com/ssl-hep/ServiceX_App/pull/96)?

**Comment by ivukotic** [comment]
In a small percentage of requests I see all the files are finished, dashboard shows 100%, request is still running and has one transformer. Looking at k8s, single transformer is still there, and its log has no errors. 
Last line printed is:
`INFO servicex xaod_cpp_transformer 72b31838-43c0-484d-8195-ccd5c3c41719 Metric: {"output-size": 1366836, "user-time": 8.299999999999997, "wall-time": 9.98, "total-time
": 8.909999999999997, "io-wait": 0.0, "request-id": "72b31838-43c0-484d-8195-ccd5c3c41719", "file-id": 20053, "system-time": 0.6099999999999994, "events": 35937, "file
name": "root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlasdatadisk/rucio/data15_13TeV/db/43/DAOD_PHYS.21568817._000973.pool.root.1"}
`
Looking in RMQ, queue is still there.

**Comment by ivukotic** [comment]
In the app log I find this:
`192.168.44.91 - - [11/Jun/2021:06:40:31 +0000] "PUT /servicex/internal/transformation/28891721-d79a-4bd0-96a4-a296066ad53e/files HTTP/1.1" 200 74 "-" "python-requests/2.25.0"
[2021-06-11 06:40:31,822] ERROR in app: Exception on /servicex/internal/transformation/28891721-d79a-4bd0-96a4-a296066ad53e/file-complete [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/servicex/servicex/resources/transformer_file_complete.py", line 75, in put
    if submitted_request.files_remaining <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'`

**Comment by BenGalewsky** [comment]
@AndrewEckart could this have been introduced in your database changes?
