### ISSUE TITLE
Transformer deployments not cleaned up after DID finder failure marks transform as "failed"

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#394]
**Describe the bug**

1. Submit transform
2. DID Finder finds the first number of files
3. ServiceX app spins up transformers and they start processing
4. DID Finder crashes
5. ServiceX app marks the transform as failed

Expect that the deployment of the transformer pods would be cleaned up, but it is still there.

[The example](https://servicex-release-testing-3.servicex.ssl-hep.org/transformation-request/29) I've seen can be found on testing 3.

Some log files:

From the DID finder (Submitted separate bug to try and track this down):
```
NFO servicex-release-testing-3 rucio_did_finder None Metric: {"timestamp": "2022-03-18T03:34:39.714144", "file_path": "root://xrootd.lcg.triumf.ca:1094//atlas/atlasdatadisk/rucio/mc16_13TeV/d5/48/DAOD_PHYS.23294916._000221.pool.root.1", "adler32": "e671d6a5", "file_size": 1348791821, "file_events": 0}
INFO servicex-release-testing-3 rucio_did_finder None Metric: {"timestamp": "2022-03-18T03:34:39.737866", "file_path": "root://xrootd.lcg.triumf.ca:1094//atlas/atlasdatadisk/rucio/mc16_13TeV/fd/eb/DAOD_PHYS.23294916._000223.pool.root.1", "adler32": "e320017a", "file_size": 1350507972, "file_events": 0}
ERROR servicex-release-testing-3 rucio_did_finder 344e96b4-5504-48f5-b3bc-65354790362a DID Request Failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/servicex_did_finder_lib/communication.py", line 92, in rabbit_mq_callback
    make_sync(run_file_fetch_loop)(did, servicex, info, user_callback)
  File "/usr/local/lib/python3.6/site-packages/make_it_sync/func_wrapper.py", line 63, in wrapped_call
    return _sync_version_of_function(fn, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/make_it_sync/func_wrapper.py", line 14, in _sync_version_of_function
    return loop.run_until_complete(r)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/servicex_did_finder_lib/communication.py", line 33, in run_file_fetch_loop
    async for file_info in user_callback(did, info):
  File "scripts/did_finder.py", line 75, in callback
    for file in lookup_request.lookup_files():
  File "/usr/src/app/src/servicex/did_finder/lookup_request.py", line 68, in lookup_files
    for ds_files in self.rucio_adapter.list_files_for_did(self.did):
  File "/usr/src/app/src/servicex/did_finder/rucio_adapter.py", line 128, in list_files_for_did
    if not self.report_logical_files else \
KeyError: 'url'
ERROR servicex-release-testing-3 rucio_did_finder 344e96b4-5504-48f5-b3bc-65354790362a DID request failed 'url'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/servicex_did_finder_lib/communication.py", line 92, in rabbit_mq_callback
    make_sync(run_file_fetch_loop)(did, servicex, info, user_callback)
  File "/usr/local/lib/python3.6/site-packages/make_it_sync/func_wrapper.py", line 63, in wrapped_call
    return _sync_version_of_function(fn, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/make_it_sync/func_wrapper.py", line 14, in _sync_version_of_function
    return loop.run_until_complete(r)
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/servicex_did_finder_lib/communication.py", line 33, in run_file_fetch_loop
    async for file_info in user_callback(did, info):
  File "scripts/did_finder.py", line 75, in callback
    for file in lookup_request.lookup_files():
  File "/usr/src/app/src/servicex/did_finder/lookup_request.py", line 68, in lookup_files
    for ds_files in self.rucio_adapter.list_files_for_did(self.did):
  File "/usr/src/app/src/servicex/did_finder/rucio_adapter.py", line 128, in list_files_for_did
    if not self.report_logical_files else \
KeyError: 'url'
```

And from ServiceX APP:
```
192.168.24.4 - - [18/Mar/2022:03:34:39 +0000] "PUT /servicex/internal/transformation/344e96b4-5504-48f5-b3bc-65354790362a/files HTTP/1.1" 200 73 "-" "python-requests/2.25.0"
192.168.24.4 - - [18/Mar/2022:03:34:39 +0000] "PUT /servicex/internal/transformation/344e96b4-5504-48f5-b3bc-65354790362a/files HTTP/1.1" 200 73 "-" "python-requests/2.25.0"
[2022-03-18 03:34:40,750] ERROR in transform_status: + Fatal error reported for 344e96b4-5504-48f5-b3bc-65354790362a from DID Finder: DID Request Failed for id 344e96b4-5504-48f5-b3bc-65354790362a: 'url' - 'url'
+ Fatal error reported for 344e96b4-5504-48f5-b3bc-65354790362a from DID Finder: DID Request Failed for id 344e96b4-5504-48f5-b3bc-65354790362a: 'url' - 'url'
192.168.24.4 - - [18/Mar/2022:03:34:40 +0000] "POST /servicex/internal/transformation/344e96b4-5504-48f5-b3bc-65354790362a/status HTTP/1.1" 200 5 "-" "python-requests/2.25.0"
192.168.14.137 - - [18/Mar/2022:03:34:42 +0000] "GET //servicex/transformation/344e96b4-5504-48f5-b3bc-65354790362a/status HTTP/1.1" 200 233 "-" "Python/3.9 aiohttp/3.7.4.post0"
192.168.14.137 - - [18/Mar/2022:03:34:42 +0000] "GET //servicex/transformation/344e96b4-5504-48f5-b3bc-65354790362a HTTP/1.1" 200 9469 "-" "Python/3.9 aiohttp/3.7.4.post0"
{'timestamp': '2022-03-18T04:37:19.597086', 'status-code': 'start', 'pod-name': 'transformer-344e96b4-5504-48f5-b3bc-65354790362a-5876799c475mvp', 'info': 'ATLAS xAOD CPP Transformer'}
192.168.1.7 - - [18/Mar/2022:03:37:19 +0000] "POST /servicex/internal/transformation/344e96b4-5504-48f5-b3bc-65354790362a/13359/status HTTP/1.1" 200 5 "-" "python-requests/2.24.0"
{'timestamp': '2022-03-18T04:37:23.558425', 'status-code': 'retry', 'pod-name': 'transformer-344e96b4-5504-48f5-b3bc-65354790362a-5876799c475mvp', 'info': 'Try: 1 error: Failed to transform input file root://xrootd-atlas.cr.cnaf.infn.it:1094//atlas/atlasdatadisk/rucio/mc16_13TeV/47/44/DAOD_PHYS.23294912._000001.pool.root.1: Output file /home/atlas/root:::xrootd-atlas.cr.cnaf.infn.it:1094::atlas:atlasdatadisk:rucio:mc16_13TeV:47:44:DAOD_PHYS.23294912._000001.pool.root.1 was not found -- errors: Configured GCC from: /opt/lcg/gcc/8.3.0-cebb0/x86_64-centos7/bin/gcc\nConfigured AnalysisBase from: /usr/AnalysisBase/21.2.184/InstallArea/x86_64-centos7-gcc8-opt\nConfigured GCC from: /opt/lcg/gcc/8.3.0-cebb0/x86_64-centos7/bin/gcc\nConfigured AnalysisBase from: /usr/AnalysisBase/21.2.184/InstallArea/x86_64-centos7-gcc8-opt\nxAOD::Init                INFO    Environment initialised for data access\nSampleHandler with 1 files\nSample:name=ANALYSIS,tags=()\nroot://xrootd-atlas.cr.cnaf.infn.it:1094//atlas/atlasdatadisk/rucio/mc16_13TeV/47/44/DAOD_PHYS.23294912._000001.pool.root.1\n\n\n'}
```

Note this is made even worse because there is a bug in my transformer in this test that causes it to crash and keep re-trying... which means we now have another DOS attack on ServiceX (but that is a different issue than this one).

**Comment by gordonwatts** [comment]
I've assigned @BenGalewsky as he mentioned in the meeting he would fill in the proper approach to fix this (either by fixing up something in ServiceX App or, making sure the "finish" is sent from the DID Finder).

**Comment by ponyisi** [comment]
I believe this is fixed now.
