### ISSUE TITLE
DID restarts on RMQ timeout

### ISSUE THREAD

**Issue by ivukotic** [ssl-hep/ServiceX#548]
DID finder restarts for larger datasets:

WARNING xaod rucio_did_finder None Received remote Channel.Close (406): 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
CRITICAL xaod rucio_did_finder None Received METHOD frame for unregistered channel 1 on <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fb1fe1bdd30> params=<URLParameters host=xaod-rabbitmq port=5672 virtual_host=/ ssl=False>>
INFO xaod rucio_did_finder None Done running rucio DID finder
Traceback (most recent call last):
  File "/usr/src/app/scripts/did_finder.py", line 87, in <module>
    run_rucio_finder()
  File "/usr/src/app/scripts/did_finder.py", line 78, in run_rucio_finder
    start_did_finder('rucio',
  File "/usr/lib/python3.9/site-packages/servicex_did_finder_lib/communication.py", line 280, in start_did_finder
    init_rabbit_mq(
  File "/usr/lib/python3.9/site-packages/servicex_did_finder_lib/communication.py", line 197, in init_rabbit_mq
    _channel.start_consuming()
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 834, in process_data_events
    self._dispatch_channel_events()
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 566, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1493, in _dispatch_events
    consumer_info.on_message_callback(self, evt.method,
  File "/usr/lib/python3.9/site-packages/servicex_did_finder_lib/communication.py", line 193, in <lambda>
    on_message_callback=lambda c, m, p, b: rabbit_mq_callback(
  File "/usr/lib/python3.9/site-packages/servicex_did_finder_lib/communication.py", line 168, in rabbit_mq_callback
    channel.basic_ack(delivery_tag=method.delivery_tag)
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 2113, in basic_ack
    self._flush_output()
  File "/usr/lib/python3.9/site-packages/pika/adapters/blocking_connection.py", line 1340, in _flush_output
    raise self._closing_reason  # pylint: disable=E0702
pika.exceptions.ChannelClosedByBroker: (406, 'PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more')

**Comment by ponyisi** [comment]
This should have been fixed with the `celery` architecture.
