### ISSUE TITLE
Accessing servicex-int gives internal server error

### ISSUE THREAD

**Issue by ketan96-m** [ssl-hep/ServiceX#841]
I went and changed the globus secrets and client id (supervised by @ivukotic )
On trying to log to the servicex-int instance gave unauthorized error
```
Defaulted container "servicex-release-int-servicex-app" out of: servicex-release-int-servicex-app, check-postgresql (init)
INFO servicex-release-int servicex_app Initialized logging
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO servicex-release-int servicex_app Initialized logging
INFO servicex-release-int servicex_app Initialized logging
INFO servicex-release-int servicex_app Initialized logging
INFO servicex-release-int servicex_app Initialized logging
INFO servicex-release-int servicex_app Initialized logging
ERROR servicex-release-int servicex_app Exception on /auth-callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/servicex/servicex_app/web/auth_callback.py", line 29, in auth_callback
    tokens = client.oauth2_exchange_code_for_tokens(code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 220, in oauth2_exchange_code_for_tokens
    return self.current_oauth2_flow_manager.exchange_code_for_tokens(auth_code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/flow_managers/authorization_code.py", line 119, in exchange_code_for_tokens
    return self.auth_client.oauth2_token(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 396, in oauth2_token
    self.post(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 156, in post
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 296, in request
    raise self.error_class(r)
globus_sdk.services.auth.errors.AuthAPIError: ('POST', 'https://auth.globus.org/v2/oauth2/token', 'Basic', 401, 'UNAUTHORIZED', 'Basic auth failed', 'a94fdcad-4e14-4e56-b5ae-b2a2b5668c4a')
ERROR servicex-release-int servicex_app Exception on /auth-callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/servicex/servicex_app/web/auth_callback.py", line 29, in auth_callback
    tokens = client.oauth2_exchange_code_for_tokens(code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 220, in oauth2_exchange_code_for_tokens
    return self.current_oauth2_flow_manager.exchange_code_for_tokens(auth_code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/flow_managers/authorization_code.py", line 119, in exchange_code_for_tokens
    return self.auth_client.oauth2_token(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 396, in oauth2_token
    self.post(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 156, in post
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 296, in request
    raise self.error_class(r)
globus_sdk.services.auth.errors.AuthAPIError: ('POST', 'https://auth.globus.org/v2/oauth2/token', 'Basic', 401, 'UNAUTHORIZED', 'Basic auth failed', '308912ba-5db2-4d95-8e5f-ff526c3e8903')
ERROR servicex-release-int servicex_app Exception on /auth-callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/servicex/servicex_app/web/auth_callback.py", line 29, in auth_callback
    tokens = client.oauth2_exchange_code_for_tokens(code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 220, in oauth2_exchange_code_for_tokens
    return self.current_oauth2_flow_manager.exchange_code_for_tokens(auth_code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/flow_managers/authorization_code.py", line 119, in exchange_code_for_tokens
    return self.auth_client.oauth2_token(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 396, in oauth2_token
    self.post(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 156, in post
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 296, in request
    raise self.error_class(r)
globus_sdk.services.auth.errors.AuthAPIError: ('POST', 'https://auth.globus.org/v2/oauth2/token', 'Basic', 401, 'UNAUTHORIZED', 'Basic auth failed', '0f429f54-7904-471c-bfd6-fca9f89f4afe')
ERROR servicex-release-int servicex_app Exception on /auth-callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/servicex/servicex_app/web/auth_callback.py", line 29, in auth_callback
    tokens = client.oauth2_exchange_code_for_tokens(code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 220, in oauth2_exchange_code_for_tokens
    return self.current_oauth2_flow_manager.exchange_code_for_tokens(auth_code)
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/flow_managers/authorization_code.py", line 119, in exchange_code_for_tokens
    return self.auth_client.oauth2_token(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/services/auth/client/base_login_client.py", line 396, in oauth2_token
    self.post(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 156, in post
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/globus_sdk/client.py", line 296, in request
    raise self.error_class(r)
globus_sdk.services.auth.errors.AuthAPIError: ('POST', 'https://auth.globus.org/v2/oauth2/token', 'Basic', 401, 'UNAUTHORIZED', 'Basic auth failed', '552e5dec-ed57-45bc-8ecc-c98060c71eba')
```

**Comment by ponyisi** [comment]
Fixed
