### ISSUE TITLE
`app.auth: false` settings doesnt work anymore with BEARER_TOKEN env variable configured in enviroment 

### ISSUE THREAD

**Issue by oshadura** [ssl-hep/ServiceX#874]
While deploying the new release 1.5.1, we would like to disable the authentification with `app.auth: false`. At the same time in the user environment at the facility we already have defined `BEARER_TOKEN` (xcache bearer token):
```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~$ env | grep BEARER
BEARER_TOKEN_FILE=/etc/cmsaf-secrets-chown/access_token
```
Looks like with disabled authentification, servicex still tries to pick up wrong token:
```
ERROR opendataaf-servicex servicex_app Got exception while submitting transformation request
Traceback (most recent call last):
  File "/home/servicex/servicex_app/resources/transformation/submit.py", line 145, in post
    user = self.get_requesting_user()
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 340, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 128, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 556, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 95, in _decode_jwt
    decoded_token = jwt.decode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 211, in decode
    decoded = self.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 152, in decode_complete
    decoded = api_jws.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 210, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 304, in _verify_signature
    raise InvalidAlgorithmError("The specified alg value is not allowed")
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed extra: {'requestId': '04c440b6-cf2d-42d1-9799-e46f93378955'}
ERROR opendataaf-servicex servicex_app Got exception while submitting transformation request
Traceback (most recent call last):
  File "/home/servicex/servicex_app/resources/transformation/submit.py", line 145, in post
    user = self.get_requesting_user()
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 340, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 128, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 556, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 95, in _decode_jwt
    decoded_token = jwt.decode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 211, in decode
    decoded = self.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 152, in decode_complete
    decoded = api_jws.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 210, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 304, in _verify_signature
    raise InvalidAlgorithmError("The specified alg value is not allowed")
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed extra: {'requestId': '76bc42ee-c5d9-42f5-84a7-5fbf872c2369'}
```

**Comment by ponyisi** [comment]
Hi @oshadura - is this still reflecting the situation?

**Comment by ponyisi** [comment]
Hi @oshadura - is this still relevant?

**Comment by oshadura** [comment]
Hi @ponyisi! I was trying to update ServiceX version (to 1.6.1) and sadly I can confirm this is still an issue. I was running https://servicex-frontend.readthedocs.io/en/stable/examples.html#func-adl-uproot-query-example with BEARER_TOKEN_FILE available :
```
[cms-jovyan@jupyter-oksana-shadura-cern-ch---becc997e idap-200gbps]$ env | grep BEARER_TOKEN
BEARER_TOKEN_FILE=/etc/cmsaf-secrets-chown/access_token
```
and it crashed with:
```
ERROR cmsaf-servicex servicex_app Exception on /token/refresh [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 339, in _decode_jwt_from_request
    encoded_token, csrf_token = get_encoded_token_function()
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 219, in _decode_jwt_from_headers
    raise InvalidHeaderError(msg)
flask_jwt_extended.exceptions.InvalidHeaderError: Bad Authorization header. Expected 'Authorization: Bearer <JWT>'
```

Unsetting variable helps to run code succesfully.

**Comment by oshadura** [comment]
I will switch for now to have an `app.auth:True` since we are testing CMS finally.

**Comment by oshadura** [comment]
retrying with 1.7.3-rc.3 with `auth:false` and with BEARER_TOKEN_FILE env variable defined, I see as an output after transformation:
```
Files: {'FuncADL_Uproot_Dict1': Invalid GuardList: RuntimeError('ServiceX WebAPI Error during transformation submission: 500 - Something went wrong (The specified alg value is not allowed)')}
```
in app logs I see:
```
INFO cmsaf-servicex servicex_app Transformation request submitted! extra: {'requestId': 'a7711d9d-0c27-4d43-bc44-ac410c8dc2cf'}
INFO cmsaf-servicex servicex_app FileComplete extra: {'requestId': 'a7711d9d-0c27-4d43-bc44-ac410c8dc2cf', 'file-id': 1, 's3-object-name': 'none', 'metric': {'requestId': 'a7711d9d-0c27-4d43-bc44-ac410c8dc2cf', 'file-path': 'root://xcache.cmsaf-dev.flatiron.hollandhpc.org//store/mc/RunIISummer20UL18NanoAODv9/DYJetsToLL_M-50_HT-100to200_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/70000/92DF66B4-2A9E-4A49-8B43-A1B2F4B24379.root', 's3-object-name': 'none', 'file-id': 1, 'status': 'failure', 'total-time': 0.8266241550445557, 'total-events': 0, 'total-bytes': 0, 'avg-rate': 0.0, 'place': {'host_name': 'c2405.shor.hcc.unl.edu', 'site': 'unknown'}}}
INFO cmsaf-servicex servicex_app Request completed. Shutting down transformers extra: {'requestId': 'a7711d9d-0c27-4d43-bc44-ac410c8dc2cf'}
INFO cmsaf-servicex servicex_app Stopping workers connected to transformer-a7711d9d-0c27-4d43-bc44-ac410c8dc2cf
[2025-10-24 09:27:04,569: INFO/MainProcess] Canceling queue transformer-a7711d9d-0c27-4d43-bc44-ac410c8dc2cf
INFO cmsaf-servicex servicex_app FileComplete. Request state. extra: {'requestId': 'a7711d9d-0c27-4d43-bc44-ac410c8dc2cf', 'file-id': 1, 's3-object-name': 'none', 'files_remaining': 0, 'files_completed': 0, 'files_failed': 1, 'report_processed_time': 0.07966160774230957}
ERROR cmsaf-servicex servicex_app Got exception while submitting transformation request
Traceback (most recent call last):
  File "/home/servicex/servicex_app/resources/transformation/submit.py", line 163, in post
    user = self.get_requesting_user()
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 340, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 128, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 557, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/usr/local/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 96, in _decode_jwt
    decoded_token = jwt.decode(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 222, in decode
    decoded = self.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jwt.py", line 156, in decode_complete
    decoded = api_jws.decode_complete(
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 220, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/local/lib/python3.10/site-packages/jwt/api_jws.py", line 315, in _verify_signature
    raise InvalidAlgorithmError("The specified alg value is not allowed")
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed extra: {'requestId': '6fde833d-3cbb-4fb5-b8ff-4b318c574f4b'}
``` 
unseting variable in notebook helps:
```
import os
os.environ.pop('BEARER_TOKEN_FILE', None)
```

**Comment by bbockelm** [comment]
@ponyisi - has anyone had an opportunity to triage this one?  Any thoughts how to move forward?

**Comment by ponyisi** [comment]
@bbockelm yes, we're looking at it. As usual we're a bit limited by not being able to try things out directly in the UNL system.

If it's possible to share one of the UNL bearer tokens, that would be very helpful. I am concerned that it may be using a signing algorithm that is unsupported by our server libraries.

**Comment by bbockelm** [comment]
Yeah, that's a piece of cake.  The good news is this is simply an IAM token - you should be able to get one from the USATLAS IAM as well.

Here's the raw JWT with the private piece redacted:

```
eyJraWQiOiJyc2EyIiwiYWxnIjoiUlMyNTYifQ.eyJ3bGNnLnZlciI6IjEuMCIsInN1YiI6ImU2MDgyNTJkLWU4MTctNDA3MS1iMTVjLTFhNzJmZTU1N2IzZiIsImF1ZCI6Imh0dHBzOlwvXC93bGNnLmNlcm4uY2hcL2p3dFwvdjFcL2FueSIsIm5iZiI6MTc2MTY2NDE5OSwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MgcHJvZmlsZSBzdG9yYWdlLnJlYWQ6XC8gZW1haWwiLCJpc3MiOiJodHRwczpcL1wvY21zLWF1dGguY2Vybi5jaFwvIiwiZXhwIjoxNzYxNjg1Nzk5LCJpYXQiOjE3NjE2NjQxOTksImp0aSI6ImVkNGYzY2YwLTIzZGMtNDhmNC05NjEyLWE3ZmE2YjJiYmM1MyIsImNsaWVudF9pZCI6IjU0NTZjMjVkLWI3MzgtNGRiNS05ZWEyLTRmOTQ2YmZkMmE4YiJ9.<redacted>
```

The decoded part is:

Headers:
```
{
  "kid": "rsa2",
  "alg": "RS256"
}
```

Payload:
```
{
  "wlcg.ver": "1.0",
  "sub": "e608252d-e817-4071-b15c-1a72fe557b3f",
  "aud": "https://wlcg.cern.ch/jwt/v1/any",
  "nbf": 1761664199,
  "scope": "openid offline_access profile storage.read:/ email",
  "iss": "https://cms-auth.cern.ch/",
  "exp": 1761685799,
  "iat": 1761664199,
  "jti": "ed4f3cf0-23dc-48f4-9612-a7fa6b2bbc53",
  "client_id": "5456c25d-b738-4db5-9ea2-4f946bfd2a8b"
}
```

The algorithm is `RS256` which is the most common signing algorithm for keypair-signed JWTs (`HS256` being the popular one for symmetric signatures).  The JWT library is going to support that.

However, most JWT libraries these days want you to explicitly list the acceptable algorithms (sometimes in the config, sometimes in the API).  Google suggests, in the app config:

```
app.config["JWT_DECODE_ALGORITHMS"] = ["HS256", "RS256"]
```

for example.

**Comment by ponyisi** [comment]
@bbockelm thanks, that will probably do it.

**Comment by bbockelm** [comment]
Wonderful, thanks @MattShirley.

@oshadura - have you been able to confirm the fix?

**Comment by oshadura** [comment]
@bbockelm, @MattShirley is looking into other issue: https://github.com/ssl-hep/ServiceX/issues/1199
