### ISSUE TITLE
DID finder crashes when no scope is given in the did

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX#88]
**Describe the bug**
Submit a request for something with no scope, like "mc16_13TeV.311309.MadGraphPythia8EvtGen_A14NNPDF31LO_HSS_LLP_mH125_mS5_ltlow.deriv.DAOD_EXOT15.e7270_e5984_s3234_r9364_r9315_p3795", the DID finder crashes. Further, the crash happens and nothing is reported back to the user.

**To Reproduce**
1. Submit a request similar to:
```
    response = requests.post(f'{running_backend}/transformation', json={
        "did": "mc16_13TeV.311309.MadGraphPythia8EvtGen_A14NNPDF31LO_HSS_LLP_mH125_mS5_ltlow.deriv.DAOD_EXOT15.e7270_e5984_s3234_r9364_r9315_p3795",
        "selection": "(call ResultTTree (call Select (call SelectMany (call EventDataset (list 'localds:bogus')) (lambda (list e) (call (attr e 'Jets') 'AntiKt4EMTopoJets'))) (lambda (list j) (/ (call (attr j 'pt')) 1000.0))) (list 'JetPt') 'analysis' 'junk.root')",
        "image": "sslhep/servicex_xaod_cpp_transformer:develop",
        "result-destination": "object-store",
        "result-format": "root-file",
        "chunk-size": 1000,
        "workers": 5
    })
```
1. See error

**Expected behavior**
I think there are two bugs:
1. The DID without the scope, at least for ATLAS, should be just fine to use. Especially given the context that this is known to be ATLAS.
1. The error needs to be reported back to the user. At the very least a test should be created in the App that generates an error and make sure it gets back to the user in the DID finder, and the DID finder should be updated to report errors, and not just crash.

**Screenshots**
Here is the dump:
```
---->  {'request_id': '18b51a6e-6b0b-42a9-9c47-762a0791141d', 'did': 'mc16_13TeV.311309.MadGraphPythia8EvtGen_A14NNPDF31LO_HSS_LLP_mH125_mS5_ltlow.deriv.DAOD_EXOT15.e7270_e5984_s3234_r9364_r9315_p3795', 'service-endpoint': 'http://servicex-integrated-testing-servicex-app:8000/servicex/transformation/18b51a6e-6b0b-42a9-9c47-762a0791141d'}
---> mc16_13TeV.311309.MadGraphPythia8EvtGen_A14NNPDF31LO_HSS_LLP_mH125_mS5_ltlow.deriv.DAOD_EXOT15.e7270_e5984_s3234_r9364_r9315_p3795
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "scripts/did_finder.py", line 188, in process_did_request
    replica_client, max_workers=max_workers):
  File "scripts/did_finder.py", line 67, in file_replicas
    files = list_files_for_did(parse_did(did), _did_client)
  File "/usr/src/app/did_finder/rucio_ops.py", line 38, in parse_did
    d['scope'], d['name'] = did.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by gordonwatts** [comment]
Did this get fixed?
